### ISSUE TITLE
PA Review {Tracks - users can add lyrics for various tracks}

### ISSUE THREAD

**Issue by JeffreyMJordan** [JeffreyMJordan/Genius#4]

**Comment by LochandQuay** [comment]
@JeffreyMJordan 

A few questions/comments: 
- [x] I'd prefer more whitespace on the sides of the lyrics/annotations area
- [x] I think some more line spacing would also improve readability. And slightly larger font.
- [ ] The lyrics div should probably be a bit wider as well. 
- [ ] The form looks pretty good. I would have some kind of hover on the submit button. 
- [ ] On your form, I think you either need placeholders or labels above the input fields, but not really both. Especially when they're the exact same but in different fonts. It looks off to me and it makes it hard for me to request additional padding on the left side of the inputs because it would offset the same text above it. 

Side note: A lot of my comments are really looking at what makes Genius' lyrics page read well.

**Comment by JeffreyMJordan** [comment]
Letting them edit the lyrics would mess with my annotation system, so this was a conscious decision. I'll get on that styling!
